### ISSUE TITLE
Distribution does not include file indicated by package.json

### ISSUE THREAD

**Issue by nathanchapman** [pritishvaidya/read-time-estimate#1]
Really cool project! 🚀 

Just a heads up:

`const readTimeEstimate = require('read-time-estimate')` currently fails because the `main` file indicated in `package.json` (`dist/index.umd.js`) isn't actually part of the distribution build.

This results in the following error:
`Module not found: Error: Can't resolve 'read-time-estimate'`

The directory structure looks like this:
![image](https://user-images.githubusercontent.com/4032071/52906216-db321680-320c-11e9-9793-7e66cd17cb72.png)

For now, using `const readTimeEstimate = require('read-time-estimate/dist/read-time-estimate')` works, but is definitely not ideal

I'd be happy to help out as well 👍

**Comment by pritishvaidya** [comment]
Yes, you're right. I never meant to use `.umd` for the index file. I'll update it with `.cjs` in the next version change.

**Comment by pritishvaidya** [comment]
I have published a minor [fix](https://www.npmjs.com/package/read-time-estimate) for it.

**Comment by nathanchapman** [comment]
@pritishvaidya Thank you!
