### ISSUE TITLE
How do I use it in my javascript code

### ISSUE THREAD

**Issue by kapooramit** [pritishvaidya/read-time-estimate#11]
Hi,

I am a little lost here. I am unable to find clear instructions on how to include it other than using npm which I don't use. How do I include it in my project and then invoke it?

-Amit

**Comment by pritishvaidya** [comment]
You can either clone the repository and use the files or use npm / yarn

**Comment by kapooramit** [comment]
Thanks. But I still find it difficult to understand how to use it. See this: https://github.com/michael-lynch/reading-time. This has all I needed (documentation and features( but it started giving me error on certain pages and I had to stop using it. 

I am looking for how do I get the value and how can I insert it in my page? Also, how do I pass the input clas/id/div/element. Usually - it is article, but it could be anything else. 

Can you help and provide more details? The logic you have used is very practical and I would like to use the script. 

-Amit

**Comment by pritishvaidya** [comment]
You can just import the file from src/index.js and use it according to the example after cloning the repo
